"""Constants shared by the HOD26 V4 Co-DINO implementation."""

from __future__ import annotations

HOD26_CLASSES = (
    "apple",
    "apple_plastic",
    "badminton",
    "banana",
    "banana_plastic",
    "car",
    "car_toy",
    "charger_head",
    "e-bike",
    "egg",
    "egg_plastic",
    "egg_wood",
    "orange",
    "orange_plastic",
    "people",
    "rubik",
    "stone_block",
    "table_tennis",
)

COCO_CLASSES = (
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "dining table",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
)

# Classifier rows are only an initialization prior. Every row remains fully
# trainable. Shape/material analogues are used when COCO has no exact class.
HOD26_TO_COCO = {
    "apple": ("apple",),
    "apple_plastic": ("apple",),
    "badminton": ("tennis racket",),
    "banana": ("banana",),
    "banana_plastic": ("banana",),
    "car": ("car",),
    "car_toy": ("car",),
    "charger_head": ("cell phone", "remote", "mouse"),
    "e-bike": ("bicycle", "motorcycle"),
    "egg": ("sports ball",),
    "egg_plastic": ("sports ball",),
    "egg_wood": ("sports ball",),
    "orange": ("orange",),
    "orange_plastic": ("orange",),
    "people": ("person",),
    "rubik": ("book", "clock", "sports ball"),
    "stone_block": ("book", "suitcase"),
    "table_tennis": ("sports ball",),
}

WEAK4_CLASSES = ("car", "e-bike", "people", "stone_block")
WEAK4_IDS = tuple(HOD26_CLASSES.index(name) for name in WEAK4_CLASSES)

OFFICIAL_CODETR_COMMIT = "26653521e47157fdd819e764b4bb949057ea9f3b"
OFFICIAL_CHECKPOINT_SHA256 = (
    "733d2ccde180a55151a68a6cab7c9f42b117d24d38d6197b37caf3189243256c"
)
OFFICIAL_CHECKPOINT_URL = (
    "https://huggingface.co/zongzhuofan/co-detr-vit-large-coco/"
    "resolve/main/pytorch_model.pth"
)
